### ISSUE TITLE
Region Schema

### ISSUE THREAD

**Issue by tthverst** [SO11e/ZB_API#11]
A region should have the following properties:
- Name (String, Required)
- Manager (User, Required)
- isActive (Boolean, Required)
- Zipcodes ([String], Required)

**Comment by Lwra93** [comment]
Welke velden zijn er required?

**Comment by tvandoorn** [comment]
Graag zou ik hier ook nog het volgende zien:

- Manager (required, referentie naar user)
- Status (required, boolean)
- Zipcodes (required, array van strings)

**Comment by Lwra93** [comment]
Pullrequest staat klaar. Pullrequest #30

**Comment by Lwra93** [comment]
Pullrequest gesloten
