### ISSUE TITLE
Issue Schema

### ISSUE THREAD

**Issue by tthverst** [SO11e/ZB_API#17]
#An issue should have the following properties:
- Street name (String)
- House number (String)
- Postal/Zip code (String)
- City (String)
- Description (String, Required)
- Date created (Date, Required)
- Date resolved (Date)
- Coordinates{
    Latitude (Number, Required),
    Longitude (Number, Required)}

**Comment by Lwra93** [comment]
Welke velden zijn required?

**Comment by Lwra93** [comment]
Done.
