### ISSUE TITLE
RoutesWalked Schema

### ISSUE THREAD

**Issue by luuk909** [SO11e/ZB_API#20]
Om op de kaart te laten zien wat er allemaal gelopen is.

- UserId (objectId)
- RegionId
- Waypoints [{
     latitude (Number),
     longitude (Number)}]

Alles required

**Comment by Lwra93** [comment]
Welke velden zijn required?

**Comment by Lwra93** [comment]
Pullrequest staat klaar. Graag checken! Pullrequest #31

**Comment by Lwra93** [comment]
Pullrequest gelsoten
