### ISSUE TITLE
Route /users - HTTP POST

### ISSUE THREAD

**Issue by bas1494** [SO11e/ZB_API#24]

**Comment by Lwra93** [comment]
Is dit niet hetzelfde als de /signup route?
Dan is het miss beter om die route te hernoemen naar /users en /signup weg te halen?

**Comment by tvandoorn** [comment]
Signup kan denk ik wel weg, want we willen niet dat randoms kunnen registreren. Eigenlijk zou alleen een regiobeheerder users moeten kunnen maken

**Comment by Lwra93** [comment]
Prima. Haal ik signup eruit en gaat er een middleware op.

**Comment by Lwra93** [comment]
Klaar. PR #34  staat klaar voor merge. Graag ff checken.

**Comment by Lwra93** [comment]
Gemerged.
