### ISSUE TITLE
Reports schema

### ISSUE THREAD

**Issue by bas1494** [SO11e/ZB_API#28]
- Description (string, required)
- Status (enum, required)
- CreateDate (date, required)
- UpdateDate (date)
- CreateBy (string (gebruik naam ingelogde gebruiker) , required)
- Issues (array van issues(meldingen) )

**Comment by Lwra93** [comment]
In de CreateBy zal het id van de user worden opgenomen. Dan kan bij het ophalen van een report de juiste data worden teruggegeven vanuit de api. De link tussen het rapport en de user is dan iets netter denk ik.

**Comment by Lwra93** [comment]
Welke statussen moeten er in het enum? Voor nu zit er in:
- created
- send
- closed

**Comment by Lwra93** [comment]
Pullrequest staat klaar. Pullrequest #32

**Comment by Lwra93** [comment]
Pullrequest gesloten.
