### ISSUE TITLE
/users POST - swagger doc incomplete

### ISSUE THREAD

**Issue by tvandoorn** [SO11e/ZB_API#66]
Swagger doc shows 'region' key is not required. App crashes without it.

app[web.1]: events.js:160
app[web.1]:       throw er; // Unhandled 'error' event
app[web.1]:       ^
app[web.1]: ValidationError: User validation failed: region: Path `region` is required.
app[web.1]:     at MongooseError.ValidationError (/app/node_modules/mongoose/lib/error/validation.js:26:11)
app[web.1]:     at model.Document.invalidate (/app/node_modules/mongoose/lib/document.js:1591:32)
app[web.1]:     at /app/node_modules/mongoose/lib/document.js:1463:17
app[web.1]:     at validate (/app/node_modules/mongoose/lib/schematype.js:745:7)
app[web.1]:     at /app/node_modules/mongoose/lib/schematype.js:790:11
app[web.1]:     at Array.forEach (native)
app[web.1]:     at ObjectId.SchemaType.doValidate (/app/node_modules/mongoose/lib/schematype.js:750:19)
app[web.1]:     at /app/node_modules/mongoose/lib/document.js:1461:9
app[web.1]:     at _combinedTickCallback (internal/process/next_tick.js:73:7)
app[web.1]:     at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by gjgradem** [comment]
Is Fixed
